### ISSUE TITLE
Support all currencies! For pricing

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/trust-api#7]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vikmeup** [comment]
@kolya182 what's the latest on this? any progress on supporting all the currencies?

**Comment by kolya182** [comment]
@vikmeup Will be working on this today/tomorrow  along with https://github.com/TrustWallet/trust-api/issues/18

**Comment by kolya182** [comment]
Ready to use, docs https://public.trustwalletapp.com/docs/#api-Tokens
